### ISSUE TITLE
Add a branded btn color

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1050]
Add a class for `btn-brand` that uses the `$primary_color`. Bootstrap darkens on hover, so it should replicate that too.

**Comment by chrisblakley** [comment]
Starting point:
```scss
.btn-brand {background-color: $primary_color; border-color: $primary_color; color: #fff;
	&:hover {background: darken($primary_color, 10%); border-color: darken($primary_color, 10%); color: #fff;}
}
```
