### ISSUE TITLE
Add another no-icon class adder in main.js

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1071]
```js
jQuery('.no-icon:not(a)').each(function(){
	jQuery(this).find('a').addClass('no-icon');
});
```

This would eliminate the need to have this selector in style.scss (which is tough to override):
```scss
.no-icon a {border-bottom: none !important;
	&:before {display: none !important;}
}
```
