### ISSUE TITLE
Bootstrap Equal Columns Experiment

### ISSUE THREAD

**Issue by PHGterence** [chrisblakley/Nebula#1166]
## Overview

Here is a bootstrap equal columns experiment I am using currently on Gryphon. It should definitely be tested before official implementation and you may want to expand on it for the xs and xl column break points.  It is based on this [article](http://getbootstrap.com.vn/examples/equal-height-columns/).

**Pros:**
- Equal Column heights (YAY!)
- Strictly SASS/CSS
- Allows you to vertically center items in the columns

**Cons:**
- Only intended for use where all columns in row must be equal heights
- Still untested for weird side-effects
## Use:

`<div class="row equal-columns-row md-cols">`
&nbsp;&nbsp;&nbsp;&nbsp;`<div class="col-md-6"></div>`
&nbsp;&nbsp;&nbsp;&nbsp;`<div class="col-md-6"></div>`
`</div>`
## Sass:

`.equal-columns-row{ display: block;`
&nbsp;&nbsp;&nbsp;&nbsp;`.col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11{ display: block;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`@include media("sm"){ display: table-cell; float: none; };`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`.col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11{ display: block;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`@include media("md"){ display: table-cell; float: none; };`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`.col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11{ display: block;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`@include media("lg"){ display: table-cell; float: none; };`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`&.sm-cols{ @include media("sm"){ display: table; table-layout: fixed; }; }`
&nbsp;&nbsp;&nbsp;&nbsp;`&.md-cols{ @include media("md"){ display: table; table-layout: fixed; }; }`
&nbsp;&nbsp;&nbsp;&nbsp;`&.lg-cols{ @include media("lg"){ display: table; table-layout: fixed; }; }`
`}`

**Comment by chrisblakley** [comment]
Still haven't tested, but I simplified the Sass:

```scss
.equal-columns-row {display: block;
	[class*="col-sm"] {display: block; @include media("sm"){display: table-cell; float: none;};}
	[class*="col-md"] {display: block; @include media("md"){display: table-cell; float: none;};}
	[class*="col-lg"] {display: block; @include media("lg"){display: table-cell; float: none;};}

	&.sm-cols{@include media("sm"){display: table; table-layout: fixed;}; }
	&.md-cols{@include media("md"){display: table; table-layout: fixed;}; }
	&.lg-cols{@include media("lg"){display: table; table-layout: fixed;}; }
}
```
