### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by rubengc** [chrisblakley/Nebula#1195]
I worked to apply a new style to form elements and with checkboxes and radios to fit them with armony to the rest of form elements

Drop next lines directly to nebula style.scss (Only applies the style if checkbox/radio next sibling is a label element)

```css
// Text/number/email/..., selects and textarea
#content-section input:not([type="submit"]):not([type="checkbox"]):not([type="radio"]):not([type="file"]), #content-section select, #content-section textarea {
  display: inline-block;
  min-height: 32px; // Selects has small height :(
  padding: 4px 6px;
  border: 1px solid #ddd; // This border looks awesome (lighter)
}

// New checkboxes/radios look!
input[type="checkbox"], input[type="radio"] {
    display: none !important;

  + label:before {
    content: "";
    display: inline-block;
    width: 16px;
    height: 16px;
    vertical-align: text-bottom;
    margin-right: 6px;
    background-color: #fff;
    border: 1px solid #ddd; // Uses new border color
  }

  &:checked + label:before {
    color: $primary_color;
    text-align: center;
  }
}

input[type="checkbox"]:checked + label:before {
  content: "\2713";
  font-size: 14px;
  line-height: 14px;
}

input[type="radio"] + label:before {
  border-radius: 50%;
}

input[type="radio"]:checked + label:before {
  content: "\2022";
  font-size: 36px;
  line-height: 4px;
}
```

Another style thing I see are the buttons rounded borders (coming from bootstrap), like much elements did not have rounded borders buttons looks much better if you apply to them a `border-radius: 0;`

Also a `border-radius: 20px;` looks really well (test it in the new nebula site to the button with transparent background and with borders, you will like it!)

Do you like this changes? I can submit a PR to decide the best form to apply changes you approve
