### ISSUE TITLE
Custom admin colors are hard to read sometimes

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1318]
Depending on the project's brand colors, the custom admin colors may be difficult to read.

Two possible solutions:
 - Only color the current page's link with custom background color and let WordPress color the rest.
 - Disable custom colors entirely so we rely 100% on WordPress core (like before).

![screen shot 2017-05-08 at 11 13 36 am](https://cloud.githubusercontent.com/assets/6349678/25852220/a61db028-3496-11e7-9f49-e4a0e9a8b3c9.png)

**Comment by chrisblakley** [comment]
I could add an option to the customizer or even Nebula Options for "Admin Color". Or I could also stop overthinking it... Is it possible to make custom Admin Color Schemes via the theme?

**Comment by chrisblakley** [comment]
https://codex.wordpress.org/Function_Reference/wp_admin_css_color

```php
add_action('admin_init', 'additional_admin_color_schemes');
function additional_admin_color_schemes() { 
  //Ocean
  wp_admin_css_color('ocean', 'Ocean'),
    get_template_directory_uri() . '/admin-colors/ocean/colors.min.css',
    array('#aa9d88', '#9ebaa0', '#738e96', '#f2fcff')
  );
}
```

Honestly, I don't think I'm going to look too much into this, but maybe.

**Comment by chrisblakley** [comment]
Could do something with `nebula()->sass_color()` too: https://github.com/chrisblakley/Nebula/issues/1349

**Comment by chrisblakley** [comment]
Here's a function to calculate a readable color based on an input color:

```php
function readableColor($bg){
    $r = hexdec(substr($bg, 0, 2));
    $g = hexdec(substr($bg, 2, 2));
    $b = hexdec(substr($bg, 4, 2));
	
	return ( ($r*$r*0.299 + $g*$g*0.587 + $b*$b*0.114) > pow(130, 2) )? '000000' : 'FFFFFF';
}

echo readableColor('000000'); // Output - FFFFFF
```

**Comment by chrisblakley** [comment]
Using a Sass function instead:

```scss
//Exponent
@function pow($number, $exponent){
	$value: 1;

	@if $exponent > 0 {
		@for $i from 1 through $exponent {
			$value: $value * $number;
		}
	}

	@return $value;
}

//.element {color: readable-color(#123456);}
@function readable-color($bg){
	$r: red($bg);
	$g: green($bg);
	$b: blue($bg);

	@if ( ($r*$r*0.299 + $g*$g*0.587 + $b*$b*0.114) > pow(130, 2) ){
		@return #000;
	}

	@return #fff;
}
```
