### ISSUE TITLE
conversionTracker will no longer work with 'on_sent_ok'

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1374]
CF7 is deprecating the `on_sent_ok` functionality, which will break the instructions for `conversionTracker()` which relies on it.

We can either remove `conversionTracker()` entirely and recommend each site do it's own thing for AJAX conversion tracking with AdWords, or we can find a way to make it work without `on_sent_ok`.

To make it work, we could listen for a class on the submit button that would trigger the `conversionTracker()` automatically.

**Comment by chrisblakley** [comment]
Let's also verify that this technique still works. It's been a very long time since it was needed (well before we started using child themes), so verify the iframe trick still works.

**Comment by chrisblakley** [comment]
It **also** needs to be updated to support child themes, because it only looks in the parent theme for the `thanks.html` page.

**Comment by chrisblakley** [comment]
I'm going to remove this functionality, and if we need to use it again we can re-develop it and pull it back.

Here's the code for reference:

```js
//Google AdWords conversion tracking for AJAX forms
//Contact Form 7 - Add on_sent_ok: "conversionTracker();" to Additional Settings
//Parameter should be either boolean (to use thanks.html) or string of another conversion page to use (Default: false).
function conversionTracker(conversionpage){
	if ( typeof conversionpage !== 'string' || conversionpage.indexOf('.') <= 0 ){
		conversionpage = 'thanks.html';
	}

	var iframe = document.createElement('iframe');
	iframe.style.width = '0px';
	iframe.style.height = '0px';
	document.body.appendChild(iframe);
	iframe.src = nebula.site.directory.template.uri + '/inc/conversion/' + conversionpage; //@todo "Nebula" 0: Does this need to be updated to support child themes?
};
```

```css
//Google AdWords - Remove iframe height
iframe[name='google_conversion_frame'] {height: 0 !important; width: 0 !important; line-height: 0 !important; font-size: 0 !important; margin-top: -13px; float: left;}
```
