### ISSUE TITLE
Luminosity Media Query example

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#141]
Add the luminosity media query to the documentation.

``` css
@media (luminosity: normal) {
    body {background: #f5f5f5; color: #262626;}
}

@media (luminosity: dim) {
    body {background: #e9e4e3;}
}

@media (luminosity: washed) {
    body {background: #ffffff;}
}
```
