### ISSUE TITLE
Use flexbox for sharing-links too

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1481]
Currently these are just inline block. Change them to flexbox with vertical centering and better spacing.

<img width="416" alt="screen shot 2017-08-21 at 4 10 23 pm" src="https://user-images.githubusercontent.com/6349678/29536300-3fafa6a6-868b-11e7-81b5-0232e527d44c.png">

```scss
.sharing-links {display: block;
	.nebula-social-button {display: inline-block; margin-right: 10px;
		span {vertical-align: inherit !important;}
	}
}
```
