### ISSUE TITLE
Migrate to Font Awesome 5 SVG method (currently using FA5 CSS method)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1527]
I've upgraded from Font Awesome 4.7 to Font Awesome 5 which is a major syntax change. For example, `<i class="fa fa-fw fa-home"></i>` becomes `<i class="fas fa-fw fa-home"></i>`.

Currently, Nebula uses the CSS method of implementing Font Awesome which will work exactly like it has in the past. However, I'd like to upgrade to the JavaScript implementation which will give much more advanced features. The problem is that I don't like the way the JavaScript method works with pseudo elements.

See this post: https://github.com/FortAwesome/Font-Awesome-Pro/issues/606#issuecomment-336580193

First, we'd have to add a script tag to tell Font Awesome to look for pseudo elements (not a major issue):
```js
<script>
  window.FontAwesomeConfig = {
    searchPseudoElements: true
  }
</script>
```

The problem is that Font Awesome JS then creates a new element rather than just styling the existing pseudo element. This changes the structure of the markup and it breaks the placement of the element/icon.

Until there is a better handling of pseudo classes Nebula will continue to use the CSS method. For reference, it does require a `font-weight: 900;` to be added. Note: There is inadequate documentation for pseudo elements in Font Awesome 5 altogether, so here is an example snippet of the Nebula hero search pseudo CSS:

```css
input { //...
  &:before {
    content: '\f002';
    display: inline-block;
    position: absolute;
    top: rem(9px);
    left: 7px;
    pointer-events: none;
    font-family: "Font Awesome 5 Free";
    font-weight: 900;
    font-size: rem(12px);
    line-height: 100%;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    transform: translate(0, 0);}
}
```
Note the `Font Awesome 5 Free` font family name (as opposed to the old `FontAwesome` font name). This can also use `Font Awesome 5 Solid`, `Font Awesome 5 Regular`, `Font Awesome 5 Light`, and `Font Awesome 5 Brand`.

For reference, here are some documentation links:

Calling JS Script: https://fontawesome.com/get-started/svg-with-js
Using JS: https://fontawesome.com/how-to-use/svg-with-js

Calling CSS Style: https://fontawesome.com/get-started/web-fonts-with-css
Using CSS: https://fontawesome.com/how-to-use/web-fonts-with-css

Icons: https://fontawesome.com/icons?d=gallery
Changed icon names from v4: https://fontawesome.com/how-to-use/upgrading-from-4

Also, [be on the lookout for CDNJS](https://cdnjs.com/libraries/font-awesome) to be updated to Font Awesome 5. Currently using the Font Awesome CDN, but I'd prefer to keep all the CDN domains the same.
