### ISSUE TITLE
Does setting the brand color in the Customizer affect the Admin Bar?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1545]
It isn't supposed to, but it appears that it might be due to the specificity of these:

```css
a:not(.btn):visited {color: #0098d7;} /* Line 77 of style.scss */
```

```css
a:not(.btn) {color: #0098d7 !important;} /* Line 71 of style.scss */
```
