### ISSUE TITLE
Why shouldn't I replace Bootstrap with CSS Grid?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1600]
I'm not looking to make a rash decision, and I'll probably start by using CSS Grid with Bootstrap at first and then when it is ready we can pull the trigger.

https://www.smashingmagazine.com/2017/06/building-production-ready-css-grid-layout/

CSS Grid allows for us to remove extra elements that don't do anything except structure content. **It also enhances RWD by allowing content to move before/after within media queries!**

Here's a good example: https://codepen.io/mor10/pen/NjeqyX?editors=1100
https://www.youtube.com/watch?v=lOYk_lWS9R0

https://caniuse.com/#feat=css-grid

_Note: Firefox has a grid inspector- surely Chrome devtools will get one soon._

I do like the idea of listing features that Bootstrap has that would be missed, so here are some major ones:
- Form styles
- Form validation
- Buttons
- Modals (style and JS)
- Carousels can be convenient

**Comment by chrisblakley** [comment]
This seems like a nice framework that uses CSS Grid: http://korywakefield.com/iota/

**Comment by chrisblakley** [comment]
As a note, [Bootstrap v5 will be slated to use CSS Grid](https://github.com/twbs/bootstrap/projects/11). But's it's going to be a really long time before that is even started, and the last version update took almost 2 years after _that_.

**Comment by chrisblakley** [comment]
Replacing Bootstrap would certainly help with embedding critical styles in the `<head>` as described here: https://github.com/chrisblakley/Nebula/issues/1678

**Comment by chrisblakley** [comment]
Maybe consider adding an option to use only the layout features of bootstrap?

**Comment by chrisblakley** [comment]
Here's a super simple starter grid with a header, content area, and sidebar:

```html
<div class="grid-container">
  <div class="Header edit-area">
  </div>
  <div class="Content">
  </div>
  <div class="Sidebar">
  </div>
</div>
```

```css
.grid-container {
  display: grid;
  height: 100%;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr;
  grid-template-areas: "Header Header Header" "Content Content Sidebar" "Content Content Sidebar";
}

.Header {
  display: grid;
  grid-area: Header;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  grid-template-areas: ".";
}

.Content {
  display: grid;
  grid-area: Content;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  grid-template-areas: ".";
}

.Sidebar {
  display: grid;
  grid-area: Sidebar;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  grid-template-areas: ".";
}
```
