### ISSUE TITLE
I don't think the Font Awesome CSS fallback stack is working

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1665]
It might have just been working on computers with Font Awesome actually installed... but on many computers the icons just show up as empty boxes when called from within CSS.

Current stack (not working):
```scss
$font_awesome: 'Font Awesome 5 Pro', 'Font Awesome 5 Free', 'Font Awesome 5 Brands';
```

Might need to go as far as creating several variables?

```scss
$font_awesome_solid: 'Font Awesome 5 Solid', 'Font Awesome 5 Free', 'Font Awesome 5 Brands';
$font_awesome_regular: 'Font Awesome 5 Regular', 'Font Awesome 5 Free', 'Font Awesome 5 Brands';
$font_awesome_light: 'Font Awesome 5 Light', 'Font Awesome 5 Free', 'Font Awesome 5 Brands';
$font_awesome_brands: 'Font Awesome 5 Brands';
```
I like the idea of falling back to brands on each so that it can catch if the brand is called from the wrong `fas` class, for example.

**Comment by chrisblakley** [comment]
The official documentation only has a brief mention of this, and I can't imagine many people are in the same situation as Nebula where you can't predict if you are using Pro or Free... https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

```css
  .login::before {
    font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f007";
  }

  .tps::before {
    font-family: "Font Awesome 5 Free"; font-weight: 400; content: "\f1ea";
  }

  .twitter::before {
    font-family: "Font Awesome 5 Brands"; content: "\f099";
  }
```

**Comment by chrisblakley** [comment]
Might even need to include the font weight property in the variables too...

```scss
$font_awesome_solid: 'font-family: "Font Awesome 5 Solid", "Font Awesome 5 Free"; font-weight: 900;'
$font_awesome_regular: 'font-family: "Font Awesome 5 Regular", "Font Awesome 5 Free"; font-weight: 400;'
$font_awesome_light: 'font-family: "Font Awesome 5 Light", "Font Awesome 5 Free"; font-weight: 300;'
```

Note that this means that it would no longer be called like this:
```scss
.element:before {content: "\f042"; font-family: $font_awesome;}
```

It would need to be called like this:
```scss
.element:before {content: "\f042"; $font_awesome_solid;}
```
