### ISSUE TITLE
Write a mixin to generate button colors

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1673]
I find myself constantly writing new button CSS styles when I could just include a mixin and pass the color(s) I want.

```scss
.btn.btn-brand-light,
.btn.btn-brand-light:visited {background-color: $accent_color; border-color: $accent_color; color: #fff;
	&:hover, &:focus, &:active {background: darken($accent_color, 10%); border-color: darken($accent_color, 10%); color: #fff;}
	&:focus {box-shadow: 0 0 0 0.2rem rgba($accent_color, 0.25);}
	&.active {background: $secondary_color; border-color: $secondary_color;}
}

.btn.btn-outline-brand-light,
.btn.btn-outline-brand-light:visited {color: $accent_color; background-color: transparent; background-image: none; border-color: $accent_color;
	&:hover, &:focus, &:active {color: #fff; background-color: $accent_color; border-color: $accent_color;}
}

.bg-brand-light {background-color: $accent_color !important;}
```

**Comment by chrisblakley** [comment]
Here's what I came up with:

```scss
//Add a btn and bg helper class
//@include add-color-class("accent", cyan);
//@include add-color-class("accent", purple, pink);
@mixin add-color-class($name, $color, $secondary){
	@if ( $secondary == null ){
		$secondary: $color;
	}

	.btn.btn-#{$name},
	.btn.btn-#{$name}:visited {background-color: $color; border-color: $color; color: readable-color($color);
		&:hover, &:focus {background: darken($color, 10%); border-color: darken($color, 10%); color: readable-color($color);}
		&:focus {box-shadow: 0 0 0 0.2rem rgba($color, 0.25);}
		&:active,
		&.active {background: $secondary; border-color: $secondary; color: readable-color($secondary);}
	}

	.btn.btn-outline-#{$name},
	.btn.btn-outline-#{$name}:visited {color: $color; background-color: transparent; background-image: none; border-color: $color;
		&:hover, &:focus {color: #fff; background-color: $color; border-color: $color;}
		&:active,
		&.active {background-color: $secondary; border-color: $secondary;}
	}

	.bg-#{$name} {background-color: $color !important;}
}
```
