### ISSUE TITLE
Need better support for Gutenberg button styles

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1802]
Here is an example button from WP core Gutenberg:

```html
<div class="wp-block-button">
    <a class="wp-block-button__link has-background has-primary-background-color" href="http://google.com" rel="nofollow external noopener">Download Solution Brief</a>
</div>
```

Outline:
```html
<div class="wp-block-button is-style-outline">
    <a class="wp-block-button__link has-text-color has-secondary-color has-background has-primary-background-color" href="http://google.com" rel="nofollow external noopener">Download Solution Brief</a>
</div>
```

Squared:
```html
<div class="wp-block-button is-style-squared">
    <a class="wp-block-button__link has-text-color has-secondary-color has-background has-primary-background-color" href="http://google.com" rel="nofollow external noopener">Download Solution Brief</a>
</div>
```

Corners are handled by WordPress styles, but colors need to be better supported. Also need to account for these in Google Analytics.

**Comment by chrisblakley** [comment]
Here's a starting point. I hate that `!important` tag...

```scss
//Gutenberg buttons
.wp-block-button {
	a.wp-block-button__link {@include link-colors(#fff, #ccc);
		&.has-primary-background-color {@include link-bg-colors($primary_color, darken($primary_color, 15%)); @include link-colors(readable-color($primary_color));}
		&.has-secondary-background-color {@include link-bg-colors($secondary_color, darken($secondary_color, 15%)); @include link-colors(readable-color($secondary_color));}

		&.has-primary-color {@include link-colors($primary_color, darken($primary_color, 15%));}
		&.has-secondary-color {@include link-colors($secondary_color, darken($secondary_color, 15%));}
	}

	&.is-style-outline {
		a.wp-block-button__link {background: none !important;
			&.has-primary-background-color,
			&.has-primary-color {border: 2px solid $primary_color;}
			&.has-secondary-background-color,
			&.has-secondary-color {border: 2px solid $secondary_color;}
		}
	}
}
```
