### ISSUE TITLE
Come up with a way to support wide width and full width Gutenberg image alignments

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1808]
The class `alignwide` on the `<figure>` wrapping class should extend the image inside beyond the width of the text column. The `alignfull` class is supposed to extend the image all the way to the outer boundaries of the viewport.

**Comment by chrisblakley** [comment]
This would probably necessitate the removal of the sidebar for starters.

**Comment by chrisblakley** [comment]
Here's how twentyninteen does it:

```css
.entry .entry-content > *.alignwide,
.entry .entry-summary > *.alignwide {
  margin-left: auto;
  margin-right: auto;
  clear: both;
}

@media only screen and (min-width: 768px) {
  .entry .entry-content > *.alignwide,
  .entry .entry-summary > *.alignwide {
    width: 100%;
    max-width: 100%;
  }
}

.entry .entry-content > *.alignfull,
.entry .entry-summary > *.alignfull {
  position: relative;
  left: -1rem;
  width: calc( 100% + (2 * 1rem));
  max-width: calc( 100% + (2 * 1rem));
  clear: both;
}

@media only screen and (min-width: 768px) {
  .entry .entry-content > *.alignfull,
  .entry .entry-summary > *.alignfull {
    margin-top: calc(2 * 1rem);
    margin-bottom: calc(2 * 1rem);
    left: calc( -12.5% - 75px);
    width: calc( 125% + 150px);
    max-width: calc( 125% + 150px);
  }
}
```

**Comment by chrisblakley** [comment]
Here's another, possibly more simple way to do it:
![Screen Shot 2019-04-07 at 6 44 46 PM](https://user-images.githubusercontent.com/6349678/55690890-54283180-5965-11e9-8414-6500cabc3647.png)

Note: that 'object-fit: cover' is a clever property that I didn't know about.

**Comment by patmcneil** [comment]
Here is a simple solution for .alignwide:

`.alignwide{transform:scale(1.15); margin:3.33em 0;}`

Add a breakpoint if needed, but at the minor 1.15 scale, it works fine all the way down to small screen size (without any media query).

**Comment by chrisblakley** [comment]
Here's how I do it in child themes, but I'm not sure that I want this to be the default setting for Nebula.

```html
<div class="row alignwide-enabled">
	<main id="top" class="col-md-8" role="main">
		<!-- entry content goes here... -->
```

```scss
.alignwide-enabled {justify-content: center;
	.alignwide {
		@include media('lg'){margin-left: -200px; margin-right: -200px;}
	}
}
```

**Comment by chrisblakley** [comment]
As we talk about the block editor integration more and more (as well as within companion plugins) I want to note any features that I may specifically bring into Nebula itself. For example, the Full Width template could be the one we use for this any other block editor features.

The CSS could do the negative margins like above, but the selector could be specific to either `.template-full-width` or some kind of `.allow-wide-width` parent selector.

**Comment by chrisblakley** [comment]
That Full Width template would work for pages, but would not work for posts as `single.php` would always be the template file. For child theming, we could copy the full width page template and rename to single.php but I'm wondering if there is a better way by default?

**Comment by chrisblakley** [comment]
This is what I came up with for now:

```scss
.page-template-fullwidth {
	h1 {font-size: 44px; text-align: center;}

	.entry-content,
	.entry-widgets,
	.entry-comments {padding-left: 40px; padding-right: 40px;
		> * {max-width: 640px; margin: 0 auto;} //Better selector for this?

		h2 {font-size: 32px; margin-top: 32px;}
		h3 {margin-top: 32px;}

		p {font-size: 18px; line-height: 32px; margin-top: 32px;}

		figure {margin-top: 32px;}
		img {max-width: 100%;}

		.alignwide {max-width: 900px;}
		.alignfull {max-width: none;
			&.wp-block-image {margin-left: -40px; margin-right: -40px;}
		}
	}
}
```

```html
<section id="content-section">
	<main id="top" role="main">
		<?php if ( have_posts() ) while ( have_posts() ): the_post(); ?>
			<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
				<div class="entry-content">
					<?php the_content(); ?>
				</div>
			</article>

			<?php if ( is_active_sidebar('single-post-widget-area') ): ?>
				<div id="single-post-widget-area" class="entry-widgets">
					<?php dynamic_sidebar('single-post-widget-area'); ?>
				</div>
			<?php endif; ?>

			<div class="entry-comments">
				<?php comments_template(); ?>
			</div>
		<?php endwhile; ?>
	</main><!--/col-->
</section>
```

If we were going to implement this into Nebula as a whole, it would be a major breaking change that would affect many templates and styles. This would also reduce the usage of Bootstrap considerably in the content areas of templates.
