### ISSUE TITLE
Watch for upcoming native CSS features

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1830]
A few features to watch for that will occur natively in CSS rather than needing a preprocessor like Sass:

### Custom Selectors:
https://cssdb.org/#custom-selectors
```css
@custom-selector :--heading h1, h2, h3, h4, h5, h6;
article :--heading + p {}
```

### Nesting:
https://cssdb.org/#nesting-rules
```css
article {
  & p {
    color: #333;
  }
}
```

### system-ui Font Family:
https://caniuse.com/font-family-system-ui
https://cssdb.org/#system-ui-font-family
```css
body {
  font-family: system-ui;
}
```

I really like this site to track the stages of upcoming CSS features:
https://cssdb.org/
