### ISSUE TITLE
Use font-display: swap with Google Fonts (when possible)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1873]
It seems the Lighthouse and Google Fonts teams are in the process of adding `font-display` capabilities to Google Fonts.

Ex: https://developers.google.com/web/updates/2016/02/font-display
```css
@font-face {
  font-family: 'Arvo';
  font-display: auto;
  src: local('Arvo'), url(https://fonts.gstatic.com/s/arvo/v9/rC7kKhY-eUDY-ucISTIf5PesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
}
```

I'd like to use `font-display: swap` in Nebula.

Conversation happening here: https://github.com/google/fonts/issues/358

Note: This would only apply in Nebula when a Google Font is used (still defaults to `system-ui` font stack).
