### ISSUE TITLE
Update @font-awesome mixin to include duotones

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1948]
Will need to figure out what specifics it uses (`font-weight` for example). Is it even possible to use duotones on pseudo elements (since it uses both `:before` and `:after`)? Still would be useful to have this updated.

Current mixin:
```scss
@mixin font-awesome($type: "solid"){
	@if $type == "solid" {
		font-family: "Font Awesome 5 Solid", "Font Awesome 5 Free", "Font Awesome 5 Pro", "Font Awesome 5 Brands"; font-weight: 900;
	} @else if $type == "regular" {
		font-family: "Font Awesome 5 Regular", "Font Awesome 5 Free", "Font Awesome 5 Pro", "Font Awesome 5 Brands"; font-weight: 400; //If this falls back to free, the font weight may not be compatible...
	} @else if $type == "light" {
		font-family: "Font Awesome 5 Light", "Font Awesome 5 Free", "Font Awesome 5 Pro", "Font Awesome 5 Brands"; font-weight: 300; //If this falls back to free, the font weight may not be compatible...
	} @else if $type == "free" {
		font-family: "Font Awesome 5 Free", "Font Awesome 5 Pro", "Font Awesome 5 Brands"; font-weight: 900;
	} @else if $type == "brand" {
		font-family: "Font Awesome 5 Brands"; font-weight: 400;
	}
}
```

Maybe we add another mixing for duotone colors/opacity to make that easier too?
```scss
.element {@include fa-duotone(red, 0.6, blue, 1);}
```

Related:
https://github.com/chrisblakley/Nebula/issues/1946
https://github.com/chrisblakley/Nebula/issues/1665
