### ISSUE TITLE
What Github Actions would be useful for this Nebula repo and for child theme repos?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1957]
I'm seeing a lot of cool potential with Github Actions, so I want to keep some notes here about what could be useful for this Nebula repo.

Additionally, I want to see if/how Github detects workflows in subdirectories to see if I can prep actions in the Nebula child theme without interfering with the actual actions for this repo.

I've added a `/workflows/` directory into the `/.github/` directory for Nebula and once I'm done experimenting in my test repo, I'll start committing some to Nebula.

**Comment by chrisblakley** [comment]
This is a good listing of ideas:
https://github.com/sdras/awesome-actions

Here are Actions in the Github Marketplace:
https://github.com/marketplace?type=actions

I like the idea of providing default labels, but I wouldn't want to interfere with anything a repo has setup itself. Maybe there is a way to allow this to be run manually, or maybe in the future it will not explicitly override existing labels...?
https://github.com/lannonbr/issue-label-manager-action

ESLint for JS files:
https://github.com/marketplace/actions/eslint-checks

PHPLint for PHP files:
https://github.com/marketplace/actions/php-lint

This one runs a webpagetest.org test and adds a comment to the commit (useful for Nebula repo, but also for child theme repos too):
https://github.com/JCofman/webPagetestAction

Scan code for secret strings, but this could possibly be used for debug strings too:
https://github.com/cds-snc/github-actions/tree/master/seekret

Sends an email (could work well in combination with the secret scanner above):
https://github.com/cirrus-actions/email

Execute remote SSH commands (potentially useful for #1281):
https://github.com/appleboy/ssh-action

Other interesting actions:
- This one can publish to the WordPress.org repository (for plugin development): https://github.com/10up/actions-wordpress/
- Another action for publishing to WordPress: https://github.com/lubusIN/actions/tree/master/wordpress

**Comment by chrisblakley** [comment]
It _seems_ like any actions within the child theme will not interfere with the main repo workflows– this means that the `/Nebula-Child/` subdirectory can contain workflows within its `/.github/workflows/` directory without messing up the master.

**Comment by chrisblakley** [comment]
WebPageTest Action has been implemented. Here is the yml syntax for reference:

```yml
on: push
name: Run Webpagetest
jobs:
  webPageTestActions:
    name: WebPageTestActions
    runs-on: ubuntu-latest
    steps:
      - uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: https://gearside.com/nebula/
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
``` 

Remember: YAML files cannot contain tabs!
