### ISSUE TITLE
Helper class to make any svg file act like a Font Awesome icon

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1982]
Consider a helper class in Nebula that allows any svg image to be manipulated like a Font Awesome icon. Could include documentation of how the end-developer would handle that.

**Comment by chrisblakley** [comment]
Here's what I ended up with:

```css
.nebula-fa {text-align: center; width: 1.25em; vertical-align: text-bottom;} //Make an img tag behave similar to a Font Awesome icon
```

![Screen Shot 2020-02-29 at 12 09 14 AM](https://user-images.githubusercontent.com/6349678/75601298-c0cd8280-5a87-11ea-8a61-2c5877b18eff.png)
