### ISSUE TITLE
CSS Grid layout notes

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#1991]
Here's where I'll keep my notes specifically for updating all of the templates to CSS Grid. This won't get finalized until after 1.) IE11 support has ended, and 2.) Bootstrap 5 has been released and Nebula updated to use it.

In the meantime, I want to plan this out and maybe I'll build an interim page template for testing.

Here's my thought for the basic subpage grid:
```css
.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-areas: "Navigation Navigation Navigation Navigation" "Hero Hero Hero Hero" "Content Content Content Sidebar" "Footer Footer Footer Footer";
}

.Navigation { grid-area: Navigation; }
.Hero { grid-area: Hero; }
.Content { grid-area: Content; }
.Sidebar { grid-area: Sidebar; }
```

This would give us a grid area for the navigation (which will still use the Nebula Customizer option to appear above or on top of the hero image, then the hero/header followed by the content (and sidebar) and footer.

The related issue #1990 for Bootstrap 5 update will play a part in this based on whatever features/classes/syntax they use to assist in the grid layout.

**Comment by chrisblakley** [comment]
This is another thought I had to separate the `Navigation` grid area into `Logo` and `Navigation`:

```css
.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr 1fr;
  grid-template-areas: "Logo Navigation Navigation Navigation" "Hero Hero Hero Hero" "Content Content Content Sidebar" "Footer Footer Footer Footer";
}
.Logo { grid-area: Logo; }
.Navigation { grid-area: Navigation; }
.Hero { grid-area: Hero; }
.Content { grid-area: Content; }
.Sidebar { grid-area: Sidebar; }
.Footer { grid-area: Footer; }
```

This would require more child theme changes if the design does not place the logo in the upper left.
