### ISSUE TITLE
Consider extending CF7 form uploader with a drag and drop UI

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2009]
Consider a Nebula helper than enhances Contact Form 7's file upload field with a drag and drop file uploader.

I'm thinking that we can add an invisible active area over the entire form (and give developers control over that area with a class) that allows users to drag and drop a file over it and the data is entered into the file upload field itself.

Here's some code for thought:
```js
const dropArea = document.getElementById('drop-area');

dropArea.addEventListener('dragover', (event) => {
  event.stopPropagation();
  event.preventDefault();
  // Style the drag-and-drop as a "copy file" operation.
  event.dataTransfer.dropEffect = 'copy';
});

dropArea.addEventListener('drop', (event) => {
  event.stopPropagation();
  event.preventDefault();
  const fileList = event.dataTransfer.files;
  console.log(fileList);
});
```

**Comment by chrisblakley** [comment]
This should add a class to the droparea element, the form, and even the body (?) when active... Or maybe just the body or the form and cascade any style down from there?

Then we'll need baseline styles for the droparea when active and even baseline text instruction to tell the user they can drop the file.

**Comment by chrisblakley** [comment]
I got the front-end to work great, but discovered that we can't simply modify the value of a `<input type="file" />` element with JavaScript. So we would need to AJAX the file and upload it to the server, then hijack the CF7 mail send hook to include the file (or a reference to its location) and inject it into the email.

There are plugins that are doing it exactly that way and I think that might be overkill what I would want Nebula to do– mostly because of maintenance overhead for a convenience feature.

We could consider making this a standalone Nebula feature outside of CF7 that would let users upload files but I'm not sure I want to get into security liability with Nebula...

**Comment by chrisblakley** [comment]
Here's the code I ended up with for the front-end:

```js
nebula.dragDropUpload = function(){
	if ( jQuery('.wpcf7-file').length ){
		var dropArea = document.getElementsByClassName('nebula-drop-area')[0];

		dropArea.addEventListener('dragover', function(e){ //This gets called every frame of the hover... Can we throttle it without causing a problem?
			e.stopPropagation();
			e.preventDefault();

			e.target.classList.add('dragover');
			e.dataTransfer.dropEffect = 'copy'; //Style the drag-and-drop as a "copy file" operation.
		});

		dropArea.addEventListener('drop', function(e){
			e.stopPropagation();
			e.preventDefault();

			e.target.classList.add('dropped');
			var fileList = e.dataTransfer.files;

			//Upload the files via XHR or something here... Note: Cannot fill the <input type="file"> using JavaScript!

			console.log('file list:', fileList);
		});
	}
}
```

Debug CSS that would turn into something more:
```scss
.nebula-drop-area {border: 1px solid grey;
	&.dragover {border: 1px solid green;}
	&.dropped {border: 1px solid green; background: green;}
}
```

**Comment by chrisblakley** [comment]
Well hold on another moment... This Stack Overflow answer states that this is now possible:
https://stackoverflow.com/questions/47515232/how-to-set-file-input-value-when-dropping-file-on-page

Might dive back into this.

**Comment by chrisblakley** [comment]
Alright here's what I ended up with and it works great!

```js
//Enable drag and drop uploading for Contact Form 7 file inputs
nebula.dragDropUpload = function(){
	if ( jQuery('.wpcf7-file').length ){
		//Activate drag and drop listeners for each drop area class on the page
		document.querySelectorAll('.nebula-drop-area').forEach(function(dropArea){
			//Drag over
			dropArea.addEventListener('dragover', function(e){ //This gets called every frame of the hover... Can we throttle it without causing a problem?
				e.stopPropagation();
				e.preventDefault();

				dropArea.classList.add('dragover');
				e.dataTransfer.dropEffect = 'copy'; //Style the drag-and-drop as a "copy file" operation.
			});

			//Drag out
			dropArea.addEventListener('dragleave', function(e){
				dropArea.classList.remove('dragover');
			});

			//Drop
			dropArea.addEventListener('drop', function(e){
				e.stopPropagation();
				e.preventDefault();

				dropArea.classList.remove('dragover');

				var fileInput = dropArea.querySelectorAll('.wpcf7-file')[0];
				var acceptedFiles = jQuery(fileInput).attr('accept').replace(/\s?\./g, '').split(',');
				var thisFileType = e.dataTransfer.files[0].type.replace(/\S+\//, '');

				if ( !jQuery(fileInput).attr('accept').length || (e.dataTransfer.files.length === 1 && acceptedFiles.indexOf(thisFileType) != -1) ){ //If the uploader does not restrict file types, or if only one file was uploaded and that filetype is accepted
					dropArea.classList.add('dropped');
					fileInput.files = e.dataTransfer.files; //Fill the file upload input with the uploaded file
				} else {
					nebula.temporaryClass(jQuery(dropArea), 'rejected', '', 1500);
					nebula.applyValidationClasses(jQuery(fileInput), 'invalid', true); //Show the invalid message
				}
			});
		});
	}
}
```

And the visuals:
```scss
.nebula-drop-area {position: relative; padding: 10px 25px 15px; border: 1px dotted grey; border-radius: 5px;
	* {transition: opacity 0.25s ease;}

	&:after {position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; justify-content: center; align-items: center; color: #000; font-weight: bold; pointer-events: none; transition: background-color 0.25s ease;}

	&.dragover {border: none;
		* {opacity: 0.05;}

		&:after {
			content: "Release to upload...";
			color: $success_color;
			background-color: rgba($success_color, 0.2);
			background-image: linear-gradient(90deg, $success_color 50%, transparent 50%), linear-gradient(90deg, $success_color 50%, transparent 50%), linear-gradient(0deg, $success_color 50%, transparent 50%), linear-gradient(0deg, $success_color 50%, transparent 50%);
			background-repeat: repeat-x, repeat-x, repeat-y, repeat-y;
			background-size: 15px 2px, 15px 2px, 2px 15px, 2px 15px;
			background-position: left top, right bottom, left bottom, right   top;
			animation: border-motion 2s infinite linear;

			@keyframes border-motion {
				0% {background-position: left top, right bottom, left bottom, right top;}
				100% {background-position: left 15px top, right 15px bottom, left bottom 15px, right top 15px;}
			}
		}
	}
	&.dropped {border: 1px solid $success_color;}
	&.rejected {border: 1px solid $danger_color;
		* {opacity: 0.05;}

		&:after {content: "Invalid upload."; background-color: rgba($danger_color, 0.2); color: $danger_color;}
	}
}
```

This will also work if there are multiple upload fields on the same page (as long as there are multiple form groups each with the `.nebula-drop-area` class
