### ISSUE TITLE
Style the text-fragment highlight

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2109]
Text fragment highlighting will be able to be styled with CSS soon, so prep a style for them.

![EtFvoMDXMAocfDZ](https://user-images.githubusercontent.com/6349678/106539708-7e4ccb00-64cc-11eb-9bc8-4485b78b0086.jpg)

![EtFvoOkW4AIlTXY](https://user-images.githubusercontent.com/6349678/106539709-7ee56180-64cc-11eb-9067-b56c0e6842a8.jpg)

Two trains of thought here:
- Highlight with the theme color for brand-consistency
- Highlight with yellow so it stands out (currently leaning towards this)

I'll probably use the nice yellow color that highlights on the Nebula search results page for consistency there.

**Comment by chrisblakley** [comment]
Here's what I'm starting with for now:

```scss
::target-text {background: rgba(0, 120, 171, 0.2);} //Style text fragment highlights
```
