### ISSUE TITLE
Keep an eye on the upcoming color-contrast() css property (❌ awaiting support tracking)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2152]
Looks like Safari is introducing a CSS property that would replace Nebula's `readable-color()` and `high-contrast-color()` Sass functions. Keep an eye out to see if/when other browsers support this.

```css
section {
    background: var(--bg);
    color: color-contrast(var(--bg) vs white, black);
}
```

https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/
https://css-tricks.com/exploring-color-contrast-for-the-first-time/
