### ISSUE TITLE
Iconpeek function is not updated for FA6. Either update it or remove it.

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2201]
This is not an often used functionality, and was originally designed to work with the SVG version of Font Awesome 5. So  either find a simple way to update it to work with the FA6 CSS library, or just remove the functionality altogether.

https://nebula.gearside.com/functions/iconpeek/

Here's where it stands now. Maybe changing it to stop using a ::before pseudo would be easier than screwing around with unicode font icons...

```scss
//Prepend an icon to a link that slides in on hover.
//a.element {@include iconpeek("\f054");} //Optionally pass a FontAwesome icon from http://fortawesome.github.io/Font-Awesome/icons/ using the provided unicode.
@mixin iconpeek($icon: "\f0ee", $style: var(--fa-font-solid)){
	display: inline-block; position: relative; overflow: hidden; transition: padding 0.4s easing(easeOutBack);
	&::before {content: $icon; text-rendering: auto; font-family: $style; -webkit-font-smoothing: antialiased; display: inline-block;}
	//svg {position: absolute; left: 0; transform: translate3d(-25px, 0, 0); height: 100%; transition: transform 0.4s easing(easeOutBack); will-change: transform;}

	&:hover {padding-left: 25px;
		//svg {transform: translate3d(0, 0, 0);}
	}
}
```
