### ISSUE TITLE
Add more debug CSS selectors for highlighting potential problems

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2220]
Nebula already implements a handful of CSS selectors that are activated during audit mode. There are a whole ton more that may be useful to add.

A great collection if ideas here: https://github.com/lorenzodelijser/lint-html-with-css/blob/main/linthtmlwithcss.css

This library has a lot of these: https://github.com/Heydon/REVENGE.CSS/blob/master/revenge.css

Great convos on Twitter: https://twitter.com/hashtag/lintHTMLwithCSS

A few that I like:

```scss
//Blocking user scaling
:root:has(meta[name="viewport"][content*="user-scalable-no"])::before {
    content: "This site is preventing user scaling!";
}
```

```scss
//Find outbound links that are not using noopener and noopener
[target$="blank"]:not(
    [rel],
    [rel*="noopener"],
    [rel*="noreferrer"]
){
    outline: 2px dotted red;
}
```
