### ISSUE TITLE
Watch for the CSS Anchor API

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2223]
This will prevent the need in Nebula to do overflow detection on sub-navigation menus, for example.

https://tabatkins.github.io/specs/css-anchor-position/

```css
.anchor {anchor-name: --my-anchor;}
.anchored {left: anchor(--my-anchor right);}
```

I believe this is supported in Chrome Canary right now behind the Experimental Web Platform Features flag.

https://codepen.io/jh3y/pen/WNzBXMx
