### ISSUE TITLE
Add examples of CSS masks

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#224]
Make a basic one, but then also show an advanced one (maybe an animated transparent PNG to show how it doesn't have halos around it)- like the loading animation for Gearside. http://gearside.com/

**Comment by chrisblakley** [comment]
```css
#photobar {
	width: 100%; height: 243px; background: url("/images/photobar.jpg"); background-size: cover;
	-webkit-mask-image: url("/images/curvemask.png"); -webkit-mask-size: cover;
}
```
