### ISSUE TITLE
Watch for CSS nesting to be supported [🟩 fully supported now]

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2258]
Copying over from #1830 to give it its own issue.

https://cssdb.org/#nesting-rules
```css
article {
  & p {
    color: #333;
  }
}
```

Nesting on caniuse.com: https://caniuse.com/css-nesting

![Screen Shot 2023-07-25 at 8 32 01 AM](https://github.com/chrisblakley/Nebula/assets/6349678/71879235-6c89-4d6f-b826-a3cdebe28b90)

Waiting for Firefox version 117
