### ISSUE TITLE
Watch for custom selectors in CSS (❌ awaiting support tracking)

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2259]
Splitting this up from #1830 to give it its own issue.

### Custom Selectors:
https://cssdb.org/#custom-selectors

```css
@custom-selector :--heading h1, h2, h3, h4, h5, h6;
article :--heading + p {}
```

This has been in stage 1 for a long time.
