### ISSUE TITLE
Add the Interpolate Size property to allow for animating to/from intrinsic size keywords in CSS

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2296]
https://developer.chrome.com/docs/css-ui/animate-to-height-auto

This root CSS property allows for animating to and from intrinsic size keywords like `auto`. Add this to the `:root` selector in CSS.

```css
:root {
    interpolate-size: allow-keywords;
}
```
