### ISSUE TITLE
Do I dare make an example documentation for Ooyala?

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#350]
The JS files could be included with Nebula, and I would not bundle anything outside of the examples directory, but this might be useful the few times a year that it comes up.

This uses cssbrowserselector currently. Maybe there is a way to figure out how to do it with just modernizr?

``` html
<head>
    <script src='http://player.ooyala.com/v3/0000000000000000000'></script><!-- Update branding ID -->
</head>

<body>
    <div id="lgVid1" class="simple_overlay">
        <a class="closemod close switch simplemodal-close">X</a>
        <div class="playertype1">
            <div id='playerwrapper'></div>
        </div>              
    </div>

    <a id="ooyalalink1" class="ooyalalink videomodal1 switch ovalbutton" rel="#lgVid1" href="#" data-ooyala="AAAAAAAAAAAAAAAAAA">Play Video</a><!-- Update video ID, verify which classes can be removed! -->

    <script src="js/libs/jquery.simplemodal.1.4.4.min.js"></script>
</body>
```

``` css
/* Verify what is old and what is new! */
/* Modal */
.simple_overlay {display: none;}
#lgVid1 {width: 80%; max-width: 646px; /* height: 100px; */}
.videoplayer1 {box-shadow: 3px 3px 10px 0 rgba(0, 0, 0, 0.6); border: 1px solid #000;}
    .closemod {position: absolute; top: -33px; right: 0; display: block; font-size: 24px; line-height: 33px; width: 40px; height: 33px; text-align: center; color: #fff; background: #003395; z-index: 10001;}
        .closemod:hover,
        .closemod.hover {color: #fff;}
    .lt-ie9 .closemod, .ie8 .closemod {top: -48px;}
    .ie7 .closemod {top: -33px;}
    .ie7x {display: none; font-size: 21px; font-weight: bold; margin-top: 3px;}
    .ie7 .ie7x {display: block;}
    .ie7 .closemod i {display: none;}
        .closemod:hover {cursor: pointer; background: #001c54;}
        .closemod i {margin-top: 3px; color: #fff;}
    .videooption1 #exposeMask {background: none;}
    .videotext {background: #fff; width: 610px; padding: 5px 15px 15px 15px; z-index: 9999;}

#simplemodal-container {position: fixed; top: 120px !important; width: 640px; height: auto !important; left: 50% !important; margin-left: -320px; zoom: 1; outline: 15px solid #000; outline: 15px solid rgba(0,0,0,0.4); z-index: 1002;}
.firefox #simplemodal-container {width: 670px; margin-left: -335px; outline: 0; border: 15px solid #000; border: 15px solid rgba(0,0,0,0.4);}
.ie7 #simplemodal-container {width: 640px; margin-left: -335px; outline: 0; border: 15px solid #000; border: 15px solid rgba(0,0,0,0.4);}
#simplemodal-overlay {background-color:#000;}

#playerwrapper{width:640px;height:360px; position: relative;}
#playerwrapper .video{position: static;}

.ff2 .playertype2,
.ff .playertype2,
.gecko .playertype2,
.safari .playertype2,
.chrome .playertype2,
.ie .playertype2 {display: none !important; height: 0 !important; visibility: hidden !important;}

.lt-ie9 .video {height: 100% !important; padding-bottom: 0 !important;}
```

``` js
if ( !jQuery('html').hasClass('ie8') ) {
        ooyalaVideo();
    } else {
        ooyalaVideo();
        //ooyalaVideoIE8();
    }

    function ooyalaVideo(){
        if( jQuery('.ooyalalink').length ){
            jQuery('.ooyalalink').on('click', function(e){

                e.preventDefault();

                var thisID = jQuery(this).attr('id'); //ooyalink5
                var thisOOcode = jQuery(this).data('ooyala');
                var thismovieplayer = OO.Player.create('playerwrapper', thisOOcode, {
                    height:'100%',
                    width:'100%'
                });

                jQuery('#lgVid1').modal();

                jQuery('.simplemodal-close').on('click', function(){
                    thismovieplayer.destroy();
                });
            });
        }
    }

    function ooyalaVideoIE8(){
        if( jQuery('.ooyalalink').length ){
            jQuery('.ooyalalink').on('click', function(e){

                e.preventDefault();

                jQuery('#lgVid1').modal();

            });
        }
    }
```
