### ISSUE TITLE
Make sure WYSIWYG content images have proper margin

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#38]
Something like:

```css
div.entry-content img {margin: 0 24px 12px 24px;}
div.entry-content img.alignleft {display: inline; margin-left: 0; margin-right: 24px;}
div.entry-content img.alignright {display: inline; margin-left: 24px; margin-right: 0;}
div.entry-content img.aligncenter {clear: both; display: block; margin-left: auto; margin-right: auto;}
```

These may be present (or close to it) lower in the style.css under the /* LAYOUT */ comment, but could be improved.
