### ISSUE TITLE
Space Height Shortcode

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#69]
Create a shortcode to add spacers in the WYSIWYG editor using a shortcode. The shortcode would be: 

```
[space height=8]
```

Add to functions.php

``` php
    // shortcode for space
    add_shortcode('space', 'gdl_space_shortcode');
    function gdl_space_shortcode( $atts ){
        extract( shortcode_atts(array("height" => '20'), $atts) );  

        return '<div class="clear" style=" height:' . $height . 'px;" ></div>';
    }
```

For reference, the .clear class (see if our clearfix is similar enough)

``` css
.clear {
    clear: both;
    display: block;
    overflow: hidden;
    visibility: hidden;
    width: 0;
    height: 0;
}
```
