### ISSUE TITLE
Add icons to filetypes to WYSIWYG content by default

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#695]
Consider automatically adding filetype icons to file links in the WYSIWYG by default (using ```.entry-content```).

```css
/* ==========================================================================
   Special File Type Indicators
   ========================================================================== */
a[href$=".doc"], a[href$=".docx"] {text-decoration: none; border-bottom: 1px dotted #2b5797;}
a[href$=".xls"], a[href$=".xlsx"] {text-decoration: none; border-bottom: 1px dotted #1e7145;}
a[href$=".ppt"], a[href$=".pptx"] {text-decoration: none; border-bottom: 1px dotted #d04525;}
a[href$=".pdf"] {text-decoration: none; border-bottom: 1px dotted #eb3b00;}
a[href$=".zip"], a[href$=".zipx"], a[href$=".rar"] {text-decoration: none; border-bottom: 1px dotted #777777;}
a[href$=".txt"], a[href$=".rtf"] {text-decoration: none; border-bottom: 1px dotted #777777;}

.entry-content a[href$=".doc"]:before, .entry-content a[href$=".docx"]:before,
li.icon a[href$=".doc"]:before, a.icon[href$=".doc"]:before, li.icon a[href$=".docx"]:before, a.icon[href$=".docx"]:before {content: "\f1c2"; font-family: "FontAwesome"; color: #2b5797; margin-right: 5px;}
.entry-content a[href$=".xls"]:before, .entry-content a[href$=".xlsx"]:before,
li.icon a[href$=".xls"]:before, li.icon a[href$=".xlsx"]:before {content: "\f1c3"; font-family: "FontAwesome"; color: #1e7145; margin-right: 5px;}
.entry-content a[href$=".ppt"]:before, .entry-content a[href$=".pptx"]:before,
li.icon a[href$=".ppt"]:before, a.icon[href$=".ppt"]:before, li.icon a[href$=".pptx"]:before, a.icon[href$=".pptx"]:before {content: "\f1c4"; font-family: "FontAwesome"; color: #eb3b00; margin-right: 5px;}
.entry-content a[href$=".pdf"]:before, .entry-content a[href$='.pdfx']:before,
li.icon a[href$=".pdf"]:before, a.icon[href$=".pdf"]:before, li.icon a[href$='.pdfx']:before, a.icon[href$='.pdfx']:before {content: "\f1c1"; font-family: "FontAwesome"; color: #d04525; margin-right: 5px;}
.entry-content a[href$=".zip"]:before, .entry-content a[href$=".zipx"]:before, .entry-content a[href$=".rar"]:before,
li.icon a[href$=".zip"]:before, a.icon[href$=".zip"]:before, li.icon a[href$=".zipx"]:before, a.icon[href$=".zipx"]:before, li.icon a[href$=".rar"]:before, a.icon[href$=".rar"]:before {content: '\f1c6'; font-family: "FontAwesome"; color: #777777; margin-right: 5px;}
.entry-content a[href$=".txt"]:before, .entry-content a[href$=".rtf"]:before,
li.icon a[href$=".txt"]:before, a.icon[href$=".txt"]:before, li.icon a[href$=".rtf"]:before, a.icon[href$=".rtf"]:before {content: '\f0f6'; font-family: "FontAwesome"; color: #777777; margin-right: 5px;}

a.icon:before {font-weight: normal;}
a.icon[href$=".html"] {text-decoration: none; border-bottom: 1px dotted #f1672c;}
	li.icon a[href$=".html"]:before, a.icon[href$=".html"]:before {content: '\f1c9'; font-family: "FontAwesome"; color: #f1672c; margin-right: 5px;}
a.icon[href$=".php"] {text-decoration: none; border-bottom: 1px dotted #5a68a5;}
	li.icon a[href$=".php"]:before, a.icon[href$=".php"]:before {content: '\f1c9'; font-family: "FontAwesome"; color: #5a68a5; margin-right: 5px;}
a.icon[href$=".js"] {text-decoration: none; border-bottom: 1px dotted #f1bf26;}
	li.icon a[href$=".js"]:before, a.icon[href$=".js"]:before {content: '\f1c9'; font-family: "FontAwesome"; color: #f1bf26; margin-right: 5px;}
a.icon[href$=".css"] {text-decoration: none; border-bottom: 1px dotted #30a9dc;}
	li.icon a[href$=".css"]:before, a.icon[href$=".css"]:before {content: '\f1c9'; font-family: "FontAwesome"; color: #30a9dc; margin-right: 5px;}
a.icon[href$=".swf"], a.icon[href$=".fla"] {text-decoration: none; border-bottom: 1px dotted #C31E24;}
	li.icon a[href$=".swf"]:before, a.icon[href$=".swf"]:before, li.icon a[href$=".fla"]:before, a.icon[href$=".fla"]:before {content: '\f1c9'; font-family: "FontAwesome"; color: #C31E24; margin-right: 5px;}
```
