### ISSUE TITLE
External Fonts Rendering Issue

### ISSUE THREAD

**Issue by PHGterence** [chrisblakley/Nebula#763]
External Fonts render funny. Look of Scandanaian orgin but on repaint, font goes back to normal. Google lead me to this thread: https://code.google.com/p/chromium/issues/detail?id=336476#c40
and this fix
```css
body {
	-webkit-animation-duration: 0.1s;
	-webkit-animation-name: fontfix;
	-webkit-animation-iteration-count: 1;
	-webkit-animation-timing-function: linear;
	-webkit-animation-delay: 0.1s;
}
@-webkit-keyframes fontfix{
	from{opacity: 1;}
	to{opacity: 1;}
}
```
