### ISSUE TITLE
Modernizr SASS Mixin

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#837]
Add Pat's SASS mixin for modernizr selectors.

**Comment by chrisblakley** [comment]
Make the $false parameter optional, too.

**Comment by chrisblakley** [comment]
Be sure to always add .no-js to the false return!

**Comment by chrisblakley** [comment]
Look into this modernizr mixin too. It approaches it a little differently, but might be even more flexible... Worth looking into: http://hugogiraudel.com/2014/05/12/modernizr-sass-mixin/

Their syntax:
```scss
.test {
  @include yep(opacity, csstransforms) {
    opacity: 0;
    transform: translateX(10px);
  }
  
  @include nope(opacity, csstransforms) {
    visibility: hidden;
    left: 10px;
  }
}
```
