### ISSUE TITLE
Add helper class .avoid-clicks

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#95]
``` css
.avoid-clicks {pointer-events: none;}
.allow-clicks {pointer-events: all;}
```
