### ISSUE TITLE
Better animation presets

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#963]
Consider removing animate.css from default libraries.

Add more css keyframe sets for various animations like pushing and stuff. Consider a partial file entirely for animations. Be sure to include example implementations of these animations!

Inspiration:
- http://thecssguru.freeiz.com/animate/
- https://daneden.github.io/animate.css/

**Comment by chrisblakley** [comment]
```scss
.example.active {@include prefix((animation: pushed .5s easing(easeOutBack)), webkit)}
@include keyframes(pushed){
	0% {transform: scale(1);}
	50% {transform: scale(0.95);}
	100% {transform: scale(1);}
}
```
