### ISSUE TITLE
Add example in CSS for fixed position headers with WP admin bar

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#975]
The admin bar blocks headers when they are in fixed position. Add a comment to the style.scss file to add:
```css
.admin-bar #secondarynavcon {top: 32px;}
```

To the appropriate element when it is positioned fixed.
